pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

def localProperties = new Properties().tap {
    if (file("local.properties").exists()) {
        it.load(file("local.properties").newInputStream())
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenLocal()
        google()
        mavenCentral()
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/PnX-SI/gn_mobile_maps")
            credentials {
                username = localProperties.get("gpr.user") ?: System.getenv("USERNAME")
                password = localProperties.get("gpr.key") ?: System.getenv("TOKEN")
            }
        }
    }
}

rootProject.name = "Occtax mobile"
include ':commons', ':compat', ':datasync', ':viewpager', ':occtax'